services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nistech\ContaoQualliIdLogin\:
        resource: ../src/
        exclude:
            - ../src/{DependencyInjection}
            - ../src/**/*Exception.php
        arguments:
            - '@?logger'
        tags:
            - { name: monolog.logger, channel: contao.general }

    Nistech\ContaoQualliIdLogin\OAuth2\Client\QualliIdBackendClientFactory:
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@event_dispatcher'
            - '@router'
            - '%nistech_contao_qualliid_login.contao_oauth2_clients.qualliid_backend%'
            - '@?logger'
        tags:
            - { name: monolog.logger, channel: contao.general }

    Nistech\ContaoQualliIdLogin\OAuth2\Client\QualliIdFrontendClientFactory:
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@event_dispatcher'
            - '@router'
            - '%nistech_contao_qualliid_login.contao_oauth2_clients.qualliid_frontend%'
            - '@?logger'
        tags:
            - { name: monolog.logger, channel: contao.general }
